#!/bin/bash
function red { echo -ne "\033[1;31m$1\033[0m"; tput sgr0; }

set -e 
rm -r web/
mkdir -p web/dive
mkdir -p web/dive-mt
mkdir -p web/dive-simd
mkdir -p web/dive-mt-simd

echo "The content of this directory is generated by the makeweb.sh script. All changes in this directory might get lost!" > web/README
make clean; JAVASCRIPT=1                 make -j8; cp src/dive.html src/dive.js src/dive.wasm web/dive/
make clean; JAVASCRIPT_MT=1              make -j8; cp src/dive.html src/dive.js src/dive.wasm src/dive.worker.js web/dive-mt
make clean; AUTOVECTOR=1 JAVASCRIPT=1    make -j8; cp src/dive.html src/dive.js src/dive.wasm web/dive-simd/
make clean; AUTOVECTOR=1 JAVASCRIPT_MT=1 make -j8; cp src/dive.html src/dive.js src/dive.wasm src/dive.worker.js web/dive-mt-simd

cp src/index.html web/

red "Success\n"

